# -*- coding: utf-8 -*-
"""Baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TisgA_Ihzp8hT5gaLqaKWGhe8uAtnRu0
"""

from google.colab import files
import pandas as pd
import io
import urllib.parse

# 1. Prompt file upload
print("Please upload your CSV/TSV file (must contain 'url' and 'is_phishing' columns):")
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# 2. Read data (handles both comma and tab separated automatically)
df = pd.read_csv(io.BytesIO(uploaded[filename]), sep=None, engine='python')

# 3. Clean URLs to extract just the host/domain for the API
def extract_host(url_string):
    if not str(url_string).startswith(('http://', 'https://')):
        url_string = 'http://' + str(url_string)
    return urllib.parse.urlparse(url_string).netloc

df['host'] = df['url'].apply(extract_host)
print(f"\nSuccessfully loaded {len(df)} rows.")
display(df.head(3))



full_df = df

# full_df.to_csv(output_csv, index=False)
# print(f"\nSaved {full_df.shape[1]} columns to {output_csv}")

# Automatically download to your local machine
from google.colab import files
# files.download(output_csv)
display(full_df.head(3))

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, accuracy_score
import matplotlib.pyplot as plt

# 1. Isolate the target variable
y = full_df['is_phishing']

# 2. Filter out raw text columns and metadata
drop_cols = ['url', 'host', 'is_phishing', 'code', 'error', 'unicodedetails']
X_raw = full_df.drop(columns=[c for c in drop_cols if c in full_df.columns], errors='ignore')

# 3. Force all features to be numeric and fill NaN values with 0
X = X_raw.apply(pd.to_numeric, errors='coerce').fillna(0)

print(f"Training on {X.shape[1]} numerical features...\n")

# 4. Split data (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.1, random_state=69, stratify=y
)

# 5. Train Baseline Decision Tree
# Constraining max_depth prevents the tree from massively overfitting on small datasets
dt_model = DecisionTreeClassifier(random_state=69, max_depth=4
)
dt_model.fit(X_train, y_train)

# 6. Evaluate Model
y_pred = dt_model.predict(X_test)
print("--- Model Evaluation ---")
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}\n")
print(classification_report(y_test, y_pred))

# 7. Visualize Top 10 Features
importances = pd.Series(dt_model.feature_importances_, index=X.columns)
top_features = importances.sort_values(ascending=False).head(10)

plt.figure(figsize=(8, 5))
top_features.plot(kind='barh', color='steelblue')
plt.title('Top 10 Most Important API Signals')
plt.gca().invert_yaxis()
plt.xlabel('Feature Importance')
plt.show()

from sklearn.tree import plot_tree

plt.figure(figsize=(20, 12))

# Plot the tree
plot_tree(
    dt_model,
    feature_names=X.columns,
    class_names=['Legitimate', 'Phishing'], # 0 = Legitimate, 1 = Phishing
    filled=True,
    rounded=True,
    fontsize=10,
    max_depth=3  # Change this to see deeper levels if needed
)

plt.title("Phishing Detection Decision Tree")
plt.tight_layout()
plt.show()

from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report
import matplotlib.pyplot as plt
import numpy as np

print("--- Training XGBoost Model ---")
# Initialize XGBoost Classifier
# We use eval_metric='logloss' to avoid warnings and random_state for reproducibility
xgb_model = XGBClassifier(
    n_estimators=100,
    max_depth=5,
    learning_rate=0.1,
    eval_metric='logloss',
    random_state=42
)

# Train the model
xgb_model.fit(X_train, y_train)

# Make predictions
xgb_pred = xgb_model.predict(X_test)
xgb_acc = accuracy_score(y_test, xgb_pred)

print(f"XGBoost Accuracy: {xgb_acc:.4f}\n")
print("XGBoost Classification Report:")
print(classification_report(y_test, xgb_pred))

# ==========================================
# Compare Decision Tree and XGBoost
# ==========================================
dt_acc = accuracy_score(y_test, dt_model.predict(X_test))

# Create Comparison Chart
plt.figure(figsize=(8, 5))
models = ['Decision Tree', 'XGBoost']
accuracies = [dt_acc, xgb_acc]
colors = ['#1f77b4', '#ff7f0e']

bars = plt.bar(models, accuracies, color=colors, width=0.5)
plt.ylim(0, 1.1)
plt.ylabel('Accuracy')
plt.title('Model Comparison: Decision Tree vs. XGBoost')

# Add exact accuracy values on top of the bars
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 0.02, f"{yval:.4f}", ha='center', fontweight='bold')

plt.tight_layout()
plt.show()

# ==========================================
# Feature Importance Comparison (XGBoost)
# ==========================================
xgb_importances = pd.Series(xgb_model.feature_importances_, index=X.columns)
xgb_top_features = xgb_importances.sort_values(ascending=False).head(10)

plt.figure(figsize=(8, 5))
xgb_top_features.plot(kind='barh', color='#ff7f0e')
plt.title('Top 10 Most Important API Signals (XGBoost)')
plt.gca().invert_yaxis()
plt.xlabel('Feature Importance')
plt.show()